### PR TITLE
Update Pinax Quick Start with new pinax-cli way of starting projects

### PR DESCRIPTION
**Pull request by ethankent**
This is in relation to the similarly named issue: https://github.com/pinax/pinax/issues/102

README.md seems to have already been updated (as I mentioned the my comment), so I covered the other parts of the issue. Also, I updated the mkdocs version in requirements.txt since the older version was preventing me from adequately reviewing these updates in the current issue.

### CODE REVIEW

**Comment by paltman** [comment]
Thanks!

**Comment by ethankent** [comment]
Happy to contribute!

**Comment by ethankent** [comment]
No sweat @d0ugal. Glad I could help out by spotting that.

**Comment by ossanna16** [comment]
Thanks so much for your PR @ethankent :)

**Pull request merged**
